services:
  app:
    image: zanelindquist/play-qb-app:latest
    container_name: qb-app-prod
    env_file:
      - .env.prod
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - qb_network

  db:
    image: mysql:8.0
    container_name: qb-db-prod
    env_file:
      - .env.prod
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - qb_network

  nginx:
    image: zanelindquist/play-qb-nginx:latest
    container_name: qb-nginx_proxy-prod
    ports:
      - "80:80"
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - qb_network

volumes:
  mysql_data:

networks:
  qb_network:
    driver: bridge